import { chromium } from 'playwright';
const file='/Users/gknob/dev/github/gknobloch/www-celinek-org/stardust/prototypes/index-C-cinematic.html';
const b=await chromium.launch();
const p=await (await b.newContext({viewport:{width:1440,height:900}})).newPage();
const errs=[]; p.on('pageerror',e=>errs.push(e.message));
await p.goto('file://'+file,{waitUntil:'networkidle'}); await p.waitForTimeout(1600);
const wordCount=await p.evaluate(()=>document.querySelectorAll('.hero__script .w').length);
const wordsVisible=await p.evaluate(()=>{let v=0;document.querySelectorAll('.hero__script .w').forEach(w=>{if(parseFloat(getComputedStyle(w).opacity)>0.9)v++});return v;});
const navTop=await p.evaluate(()=>getComputedStyle(document.querySelector('.site-header .container')).height);
await p.evaluate(()=>{window.__lenis?window.__lenis.scrollTo(700,{immediate:true}):window.scrollTo(0,700);}); await p.waitForTimeout(600);
const navScrolled=await p.evaluate(()=>getComputedStyle(document.querySelector('.site-header .container')).height);
const navHasScrolledClass=await p.evaluate(()=>document.getElementById('nav').classList.contains('scrolled'));
const progressW=await p.evaluate(()=>getComputedStyle(document.querySelector('.read-progress i')).transform);
const logoTop=await p.evaluate(()=>{window.__lenis&&window.__lenis.scrollTo(0,{immediate:true});return null;});
console.log('hero words split:',wordCount,'| visible after load:',wordsVisible);
console.log('nav container height: top='+navTop+'  scrolled='+navScrolled+'  (.scrolled class='+navHasScrolledClass+')');
console.log('progress bar transform at 700:',progressW);
console.log('pageerrors:',errs.length, errs.slice(0,3));
await b.close();
